name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build-images:
    strategy:
      matrix:
        version: ['3.7', '3.8', '3.9', '3.10']
    name: Build Python Docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build github3api ${{ matrix.version }} image
        run:
          docker image build --target build-image --build-arg PYTHON_VERSION=${{ matrix.version }} -t github3api:${{ matrix.version }} .
