name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build --target build-image -t github3api:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create github3api)
        docker cp $ID:/code/target/reports/github3api_coverage.xml github3api_coverage.xml
        sed -i -e 's,filename="github3api/,filename="src/main/python/github3api/,g' github3api_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: github3api_coverage.xml
